version: '2.1'
services:

  backend:
    image: otus-hiload:v1
    environment:
      DB_URI: "mysql://dbuser:123456@tcp(mysql)/hiload-db"
      SHARDED_DB_URI: "mysql://root@tcp(vtgate:15306)/messages_keyspace"
#     SHARDED_DB_URI: "mysql://dbuser:123456@tcp(mysql)/hiload-db"
#      GENERATE_FAKE_DATA: 'true'
    volumes:
      - "./mnt/storage:/opt/app/storage"
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    ulimits:
      nofile:
        soft: "262144"
        hard: "262144"

  mysql:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: "dbuser"
      MYSQL_PASSWORD: "123456"
      MYSQL_DATABASE: "hiload-db"
    command:
      --max-connections=2000 --general-log=1 --general-log-file=/var/log/mysqld.log
    ports:
      - "3306:3306"
    volumes:
      - "./mnt/mysql/data:/var/lib/mysql"
    ulimits:
      nofile:
        soft: "262144"
        hard: "262144"
#    logging:
#      driver: "none"

  consul1:
    command: agent -server -bootstrap-expect 3 -ui -disable-host-node-id -client 0.0.0.0
    hostname: consul1
    image: consul:latest
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:8600

  consul2:
    command: agent -server -retry-join consul1 -disable-host-node-id
    depends_on:
      - consul1
    expose:
      - "8400"
      - "8500"
      - "8600"
    hostname: consul2
    image: consul:latest

  consul3:
    command: agent -server -retry-join consul1 -disable-host-node-id
    depends_on:
      - consul1
    expose:
      - "8400"
      - "8500"
      - "8600"
    hostname: consul3
    image: consul:latest

  schemaload_messages_keyspace:
    command:
      - sh
      - -c
      - /script/schemaload.sh
    depends_on:
      vttablet101:
        condition: service_healthy
      vttablet201:
        condition: service_healthy
    environment:
      - TOPOLOGY_FLAGS=-topo_implementation consul -topo_global_server_address consul1:8500
        -topo_global_root vitess/global
      - WEB_PORT=8080
      - GRPC_PORT=15999
      - CELL=test
      - KEYSPACE=messages_keyspace
      - TARGETTAB=test-0000000101
      - SLEEPTIME=15
      - VSCHEMA_FILE=messages_vschema.json
      - SCHEMA_FILES=create_messages.sql
      - POST_LOAD_FILE=
      - EXTERNAL_DB=0
    image: vitess/base
    volumes:
      - ./vitess-scripts:/script

  schemaload_unsharded_keyspace:
    command:
      - sh
      - -c
      - /script/schemaload.sh
    depends_on:
      vttablet301:
        condition: service_healthy
    environment:
      - TOPOLOGY_FLAGS=-topo_implementation consul -topo_global_server_address consul1:8500
        -topo_global_root vitess/global
      - WEB_PORT=8080
      - GRPC_PORT=15999
      - CELL=test
      - KEYSPACE=unsharded_keyspace
      - TARGETTAB=test-0000000301
      - SLEEPTIME=15
      - VSCHEMA_FILE=seq_vschema.json
      - SCHEMA_FILES=create_seq.sql
      - POST_LOAD_FILE=
      - EXTERNAL_DB=0
    image: vitess/base
    volumes:
      - ./vitess-scripts:/script

  vtctld:
    command:
      - sh
      - -c
      - ' $$VTROOT/bin/vtctld -topo_implementation consul -topo_global_server_address
      consul1:8500 -topo_global_root vitess/global -cell test -web_dir $$VTTOP/web/vtctld
      -web_dir2 $$VTTOP/web/vtctld2/app -workflow_manager_init -workflow_manager_use_election
      -service_map ''grpc-vtctl'' -backup_storage_implementation file -file_backup_storage_root
      /scripts/backups -logtostderr=true -port 8080 -grpc_port 15999 -pid_file
      $$VTDATAROOT/tmp/vtctld.pid '
    depends_on:
      - consul1
      - consul2
      - consul3
    image: vitess/base
    ports:
      - 15000:8080
      - "15999"
    volumes:
      - ./vitess-scripts:/script

  vtgate:
    command:
      - sh
      - -c
      - '/script/run-forever.sh $$VTROOT/bin/vtgate -topo_implementation consul -topo_global_server_address
      consul1:8500 -topo_global_root vitess/global -logtostderr=true -port 8080 -grpc_port
      15999 -mysql_server_port 15306 -mysql_auth_server_impl none -cell test -cells_to_watch
      test -tablet_types_to_wait MASTER,REPLICA,RDONLY -gateway_implementation discoverygateway
      -service_map ''grpc-vtgateservice'' -pid_file $$VTDATAROOT/tmp/vtgate.pid -normalize_queries=true '
    depends_on:
      - vtctld
      - vttablet301
    image: vitess/base
    ports:
      - 15099:8080
      - "15999"
      - 15306:15306
    volumes:
      - ./vitess-scripts:/script

  vttablet101:
    command:
      - sh
      - -c
      - /script/vttablet-up.sh 101
    depends_on:
      - vtctld
    environment:
      - TOPOLOGY_FLAGS=-topo_implementation consul -topo_global_server_address consul1:8500
        -topo_global_root vitess/global
      - WEB_PORT=8080
      - GRPC_PORT=15999
      - CELL=test
      - KEYSPACE=messages_keyspace
      - SHARD=-80
      - ROLE=master
      - VTHOST=vttablet101
      - EXTERNAL_DB=0
      - DB_PORT=
      - DB_HOST=
      - DB_USER=
      - DB_PASS=
      - DB_CHARSET=
    healthcheck:
      interval: 30s
      retries: 15
      test:
        - CMD-SHELL
        - curl localhost:8080/debug/health
      timeout: 10s
    image: vitess/base
    ports:
      - 15101:8080
      - "15999"
      - "3306"
    volumes:
      - ./vitess-scripts:/script

  vttablet102:
    command:
      - sh
      - -c
      - /script/vttablet-up.sh 102
    depends_on:
      - vtctld
    environment:
      - TOPOLOGY_FLAGS=-topo_implementation consul -topo_global_server_address consul1:8500
        -topo_global_root vitess/global
      - WEB_PORT=8080
      - GRPC_PORT=15999
      - CELL=test
      - KEYSPACE=messages_keyspace
      - SHARD=-80
      - ROLE=replica
      - VTHOST=vttablet102
      - EXTERNAL_DB=0
      - DB_PORT=
      - DB_HOST=
      - DB_USER=
      - DB_PASS=
      - DB_CHARSET=
    healthcheck:
      interval: 30s
      retries: 15
      test:
        - CMD-SHELL
        - curl localhost:8080/debug/health
      timeout: 10s
    image: vitess/base
    ports:
      - 15102:8080
      - "15999"
      - "3306"
    volumes:
      - ./vitess-scripts:/script

  vttablet201:
    command:
      - sh
      - -c
      - /script/vttablet-up.sh 201
    depends_on:
      - vtctld
    environment:
      - TOPOLOGY_FLAGS=-topo_implementation consul -topo_global_server_address consul1:8500
        -topo_global_root vitess/global
      - WEB_PORT=8080
      - GRPC_PORT=15999
      - CELL=test
      - KEYSPACE=messages_keyspace
      - SHARD=80-
      - ROLE=master
      - VTHOST=vttablet201
      - EXTERNAL_DB=0
      - DB_PORT=
      - DB_HOST=
      - DB_USER=
      - DB_PASS=
      - DB_CHARSET=
    healthcheck:
      interval: 30s
      retries: 15
      test:
        - CMD-SHELL
        - curl localhost:8080/debug/health
      timeout: 10s
    image: vitess/base
    ports:
      - 15201:8080
      - "15999"
      - "3306"
    volumes:
      - ./vitess-scripts:/script

  vttablet202:
    command:
      - sh
      - -c
      - /script/vttablet-up.sh 202
    depends_on:
      - vtctld
    environment:
      - TOPOLOGY_FLAGS=-topo_implementation consul -topo_global_server_address consul1:8500
        -topo_global_root vitess/global
      - WEB_PORT=8080
      - GRPC_PORT=15999
      - CELL=test
      - KEYSPACE=messages_keyspace
      - SHARD=80-
      - ROLE=replica
      - VTHOST=vttablet202
      - EXTERNAL_DB=0
      - DB_PORT=
      - DB_HOST=
      - DB_USER=
      - DB_PASS=
      - DB_CHARSET=
    healthcheck:
      interval: 30s
      retries: 15
      test:
        - CMD-SHELL
        - curl localhost:8080/debug/health
      timeout: 10s
    image: vitess/base
    ports:
      - 15202:8080
      - "15999"
      - "3306"
    volumes:
      - ./vitess-scripts:/script

  vttablet301:
    command:
      - sh
      - -c
      - /script/vttablet-up.sh 301
    depends_on:
      - vtctld
    environment:
      - TOPOLOGY_FLAGS=-topo_implementation consul -topo_global_server_address consul1:8500
        -topo_global_root vitess/global
      - WEB_PORT=8080
      - GRPC_PORT=15999
      - CELL=test
      - KEYSPACE=unsharded_keyspace
      - SHARD=-
      - ROLE=master
      - VTHOST=vttablet301
      - EXTERNAL_DB=0
      - DB_PORT=
      - DB_HOST=
      - DB_USER=
      - DB_PASS=
      - DB_CHARSET=
    healthcheck:
      interval: 30s
      retries: 15
      test:
        - CMD-SHELL
        - curl localhost:8080/debug/health
      timeout: 10s
    image: vitess/base
    ports:
      - 15301:8080
      - "15999"
      - "3306"
    volumes:
      - ./vitess-scripts:/script
